import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import TopNavigation from "@/components/Navigation/top-navigation";
import { Sarabun } from "next/font/google";
import { UserProvider } from "./context/UserContext";
import { SessionProvider } from "./context/SessionContext";
import { TestProvider } from "./context/TestContext";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sarabun = Sarabun({
  weight: '400',
  subsets: ['thai', 'latin'],
  display: 'swap',
  variable: "--font-sarabun",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} > */}
        <SessionProvider>
          <UserProvider>
            <TestProvider>

            <body className={`${sarabun.variable} ${geistSans.variable} ${geistMono.variable} antialiased`} >
              <TopNavigation />
              <div className="max-w-screen-xl mx-auto mt-6 px-5 sm:px-0">
                {children}
              </div>
              <Toaster
                position="bottom-right"
                reverseOrder={false}
              />
            </body>
            
            </TestProvider>
          </UserProvider>
        </SessionProvider>
      </html>
    </>
  );
}
